AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auth0-mfa-with-passwordless-otp

  Auth0 Rules and SAM Template for a companion Web App to perform MFA with Passwordless OTP

Globals:
  Function:
    Timeout: 120

Parameters:
  CLIENT_ID:
    Type: String
  CLIENT_SECRET:
    Type: String
  AUTH0_DOMAIN:
    Type: String

Resources:
  CompanionApp:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: lambda.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          AUTH0_DOMAIN: !Sub "${AUTH0_DOMAIN}"
          AUTH0_CLIENT_ID: !Sub "${CLIENT_ID}"
          AUTH0_CLIENT_SECRET: !Sub "${CLIENT_SECRET}"
      Events:
        Root:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: get
        Resume:
          Type: Api
          Properties:
            Path: /resume
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CompanionAppURL:
    Description: "API Gateway endpoint URL for Prod stage for companion app"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
